/*
 Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 */
package projecteuler;

/**
 *
 * @author Rahul Ramkumar
 */
public class PentagonNumbers {

    boolean isPentagonal(int x) {
        double n = (Math.sqrt(24 * x + 1) + 1) / 6;

        if (n == Math.floor(n)) {
            return true;
        }
        return false;
    }

    void check() {
        int length = 2500, sum = 0, diff = 0;
        int[] pent = new int[length];

        int index = 0;
        for (int n = 1; n <= length; n++) {
            pent[index] = (n * (3 * n - 1) / 2);
            index++;
        }

        boolean found = false;
        for (int i = 0; i < length; i++) {
            for (int j = i; j < length; j++) {
                sum = pent[i] + pent[j];
                diff = pent[i] - pent[j];
                if (diff < 0) {
                    diff = -diff;
                }

                if (isPentagonal(sum) && isPentagonal(diff)) {
                    System.out.println("i:" + i + "   j: " + j);
                    System.out.println("sum: " + sum + "   difference: " + diff);
                    found = true;
                    break;
                }
            }
            if (found) {
                break;
            }
        }

    }

    public static void main(String[] args) {
        PentagonNumbers o1 = new PentagonNumbers();
        o1.check();
    }

}
