'''
Problem Statement:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

# Iterative solution.

n = int(input()) # n stands for the limit.

l = [1, 2] 

while l[-1]+l[-2] < n:
    l.append(l[-1] + l[-2]) # Generating an array of fibonacci numbers.

print(sum([i for i in l if i % 2 == 0])) # Finding the sum of the generated array based on condition (even).