'''
Problem Statement:

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

i = 1

while True:
	flag = False # Used for breaking out of nested loops.

	t = i * (i + 1) // 2

	for j in range(1, i+1):
		# Brute forcing, keeping the upper limit as (i + 1) for performace reasons.
		p = j * (3 * j - 1) // 2

		if t == p:
			for k in range(1, j+1):
				h = k * (2 * k - 1)

				if t == h:
					print(i, j, k, t)
					flag = True

		if flag:
			break

	i += 1

'''
NOTE:

This code takes a long time to complete its execution, simply because its generating the same values every time
it increments the value of i by 1.
'''